animals_list = [
    "aardvark", "alligator", "alpaca", "antelope", "armadillo", "baboon", "badger", "bandicoot", "barracuda", "bat",
    "bear", "beaver", "bison", "boa", "bobcat", "buffalo", "butterfly", "buzzard", "camel", "capybara",
    "caribou", "cassowary", "caterpillar", "catfish", "cheetah", "chinchilla", "chipmunk", "cobra", "cougar", "cow",
    "coyote", "crane", "crocodile", "crow", "deer", "dingo", "dinosaur", "dog", "dolphin", "donkey",
    "dragonfly", "duck", "eagle", "eel", "elephant", "elk", "emu", "falcon", "ferret", "flamingo",
    "fox", "frog", "gazelle", "giraffe", "goat", "goose", "gorilla", "grasshopper", "guinea-pig", "hamster",
    "hare", "hawk", "hedgehog", "hippopotamus", "hornet", "horse", "hound", "hyena", "iguana", "impala",
    "jackal", "jaguar", "jellyfish", "kangaroo", "koala", "lemur", "leopard", "lion", "llama", "lobster",
    "lynx", "macaw", "magpie", "manatee", "manta-ray", "meerkat", "mink", "monkey", "moose", "mouse",
    "mule", "narwhal", "newt", "opossum", "orangutan", "ostrich", "otter", "owl", "ox", "panda",
    "panther", "parrot", "peacock", "pelican", "penguin", "pheasant", "pig", "pigeon", "platypus", "porcupine",
    "porpoise", "possum", "prairie-dog", "puffin", "puma", "quail", "rabbit", "raccoon", "ram", "rat",
    "raven", "reindeer", "rhinoceros", "robin", "salamander", "salmon", "sandpiper", "sardine", "scorpion", "sea-lion",
    "sea-urchin", "seahorse", "seal", "shark", "sheep", "shrew", "shrimp", "skunk", "sloth", "snail",
    "snake", "sparrow", "spider", "squid", "squirrel", "starfish", "stingray", "stork", "swan", "tamarin",
    "tapir", "tarantula", "tiger", "toad", "toucan", "turkey", "turtle", "viper", "vulture", "walrus",
    "warthog", "wasp", "weasel", "whale", "wolf", "wolverine", "wombat", "woodpecker", "worm", "wren",
    "yak", "zebra", "zebu", "gorilla"
]
